version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: product purchase price information
        columns:
          - name: products_id
            description: product identifier, table primary key
          - name: purchSE_PRICE
            description: price for which product was bought
        tests:
          - unique:
              column_name: products_id
          - not_null:
              column_name: products_id
      - name: ship
        identifier: raw_gz_ship
        tests:
        - unique:
              column_name: orders_id
        - not_null:
              column_name: orders_id
      - name: sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"

        
        identifier: raw_gz_sales
        tests:
          - unique:
              column_name:  "(orders_id||pdt_id)"
models:
  - name: int_sales_margin
    description: table with added margin for sales
    columns:
      - name: orders_id
        description: part of primary key

